### ISSUE TITLE
请问可以分享一下制作这个插件时, 向gpt提问的记录(或聊天记录)吗?

### ISSUE THREAD

**Issue by abbyyhhpp** [miaobingyi/logseq-plugin-timedifference#1]
也想通过gpt制作一个logseq插件, 但是完全没编程基础, 想通过直接模仿学习, 模仿答主的流程先熟悉上手一遍, 非常感谢

**Comment by miaobingyi** [comment]
不好意思，具体的记录删除了:)

以下思路供参考：
1. 上传一个不太复杂的logseq插件给gpt，让它知道插件的大致文件目录结构
2. 清晰地描述你的需求，按点描述
3. 根据2的代码快速的验证，如果有问题直接提问，让gpt在现有的基础上修改
4. 循环往复

**Comment by abbyyhhpp** [comment]
好的, 谢谢提供思路

**Comment by abbyyhhpp** [comment]
对了, 请问下这插件还能正常使用吗, 我导入后显示这样的错误信息

This plugin #logseq-plugin-timedifference takes too long to load, affecting the application startup time and potentially causing other plugins to fail to load.

**Comment by miaobingyi** [comment]
运行命令： npm run build
